name: PPPoPP3
author: Coraline Kay
main: me.corriekay.pppopp3.Mane
version: 0.0.1
commands:
  test:
    description: derp1
  setgroup:
    description: changes a players group
    usage: /setgroup <player> <group>
    aliases: [manuadd]
    permission: pppopp3.manuadd
  list:
    description: shows a list of online players
    usage: /list
    alises: [who, online]
    permission: pppopp3.list
  groupaddperm:
    description: adds a permission to a group
    usage: /groupaddperm <perm> <group>
    permission: pppopp3.groupaddperm
  groupdelperm:
    description: deletes a groups permission
    usage: /groupdelperm <perm> <group>
    permission: pppopp3.groupdelperm
  useraddperm:
    description: adds a permission to a specific user
    usage: /useraddperm <perm> <user>
    permission: pppopp3.useraddperm
  userdelperm:
    description: deletes a permission from a user
    usage: /userdelperm <perm> <user>
    permission: pppopp3.userdelperm
  c:
    description: opens the remote chest for the world the player is currently in
    usage: /c
    aliases: [chest]
    permission: pppopp3.remotechest
  w:
    description: opens up a mobile workbench
    usage: /w
    permission: pppopp3.remotechest
  transferchest:
    description: uses the transferchest utility
    usage: /transferchest [type]
    aliases: [ts]
    permission: pppopp3.remotechest
  finddeaths:
    description: finds the deaths of mobs in a radius around you
    usage: /finddeaths <radius> <type> <days>
    permission: pppopp3.finddeaths
permissions:
  pppopp3.pm.alertgroupchange:
    description: sends messages to players alerting to group changes
    default: false