name: PPPoPP3
author: Coraline Kay
main: me.corriekay.pppopp3.Mane
version: 0.0.1
commands:
  test:
    description: derp1
  testperm:
    description: tests permission for a player
  setgroup:
    description: changes a players group
    usage: /setgroup <player> <group>
    aliases: [manuadd]
    permission: pppopp3.manuadd
  list:
    description: shows a list of online players
    usage: /list
    alises: [who, online]
    permission: pppopp3.list
  groupaddperm:
    description: adds a permission to a group
    usage: /groupaddperm <perm> <group>
    permission: pppopp3.groupaddperm
  groupdelperm:
    description: deletes a groups permission
    usage: /groupdelperm <perm> <group>
    permission: pppopp3.groupdelperm
  useraddperm:
    description: adds a permission to a specific user
    usage: /useraddperm <perm> <user>
    permission: pppopp3.useraddperm
  userdelperm:
    description: deletes a permission from a user
    usage: /userdelperm <perm> <user>
    permission: pppopp3.userdelperm
  c:
    description: opens the remote chest for the world the player is currently in
    usage: /c
    aliases: [chest]
    permission: pppopp3.remotechest
  w:
    description: opens up a mobile workbench
    usage: /w
    permission: pppopp3.remotechest
  transferchest:
    description: uses the transferchest utility
    usage: /transferchest [type]
    aliases: [ts]
    permission: pppopp3.remotechest
  finddeaths:
    description: finds the deaths of mobs in a radius around you
    usage: /finddeaths <radius> <type> <days>
    permission: pppopp3.finddeaths
  claimplot:
    description: registers an area for private creative use
    usage: /claimplot
    permissions: pppopp3.claimplot
  releaseplot:
    description: unregisters an area
    usage: /releaseplot
    permissions: pppopp3.releaseplot
  join:
    description: used to join a channel
    usage: /join <channel>
    permission: pppopp3.channel
    aliases: [ch, focus]
  leave:
    description: used to leave a channel
    usage: /leave <channel>
    permission: pppopp3.channel
  channel:
    description: lists channels, and allows a user to send a quick message to another channel without joining it
    usage: /channel or /<quick> <message>
    permission: pppopp3.channel
    aliases: [eq, equestria, d, donator, rp, roleplay, staff, ssss, nsfw]
  say:
    description: send message from the console
    usage: /say <message>
    permission: pppopp3.say
  me:
    description: sends a basic emote to the channel youre in
    usage: /me <emote>
    permission: pppopp3.me
  mute:
    description: mutes/unmutes a player
    usage: /mute <player>
    permission: pppopp3.channel
  pm:
    description: privately messages another player
    usage: /pm <player> <message>
    permission: pppopp3.pm
    aliases: [tell, msg, whisper]
  r:
    description: replies to the last user to pm you
    usage: /r <message>
    permission: pppopp3.pm
  silence:
    description: silence or unsilence someone
    usage: /silence <name>
    permission: pppopp3.silence
  silenced:
    description: lists the silenced players for a user
    usage: /silenced
    permission: pppopp3.silence
permissions:
  pppopp3.pm.alertgroupchange:
    description: sends messages to players alerting to group changes
    default: false
  pppopp3.creativeadmin:
    description: allows a person to bypass pppopp3 creative checks
    default: op